### ISSUE TITLE
migrate OLiA website and server

### ISSUE THREAD

**Issue by chiarcos** [acoli-repo/olia#6]
move from Frankfurt to GitHub, update Purls

**Comment by srl295** [comment]
Apologies if this is the wrong place to note this, but on your top README it says:

> Homepage: http://purl.org/olia

This returns a 400.

**Comment by chiarcos** [comment]
Thanks for your notice. Yes, I replaced the direct purl links with a partial redirect and now the root element doesn't resolve anymore. But links to the core ontologies (incl. http://purl.org/olia/olia.owl) resolve. For some, more peripheral ontologies, the update process is, however, still ongoing, as the original purls cannot be easily deleted (so that the partial redirect applies), but this is a long-term, manual process that fails in 80% of the trials.

**Comment by chiarcos** [comment]
Hotfix: Readme now says http://purl.org/olia/Readme.md ;) Apologies that this is raw Markdown, web page is to be restructured, as well. But links to OLiA core ontologies should work now.

**Comment by chiarcos** [comment]
Migration to GitHub pages is underway. Please check out https://acoli-repo.github.io/olia/.

**Comment by chiarcos** [comment]
Ontologies are now published via the GitHub page. `http://purl.org/olia` resolves to regular HTML. What is left here is only updating PURLs (which is a very slow manual process, and about 75% done).

**Comment by chiarcos** [comment]
Purl progress logged under #10. Otherwise, done.
